# -*- coding: utf-8 -*-
"""preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uCxUaBcuVnFqyVL6PTSyHwcGWVBRioq4
"""

import pandas as pd
from sklearn.preprocessing import OneHotEncoder, StandardScaler

# 加载数据
train_df = pd.read_csv('train.csv')
test_df = pd.read_csv('test.csv')

# 初始检查（复用EDA结果）
print("训练集缺失值：")
print(train_df.isnull().sum())  # Age:177, Cabin:687, Embarked:2
print("\n测试集缺失值：")
print(test_df.isnull().sum())   # Age:86, Cabin:327, Fare:1（额外缺失）
print(train_df.head())

# Age：用train中位数填充（避免泄露）
age_median = train_df['Age'].median()
train_df['Age'].fillna(age_median, inplace=True)
test_df['Age'].fillna(age_median, inplace=True)

# Embarked：用train模式填充
embarked_mode = train_df['Embarked'].mode()[0]
train_df['Embarked'].fillna(embarked_mode, inplace=True)
test_df['Embarked'].fillna(embarked_mode, inplace=True)

# Cabin：用'Unknown'填充
train_df['Cabin'].fillna('Unknown', inplace=True)
test_df['Cabin'].fillna('Unknown', inplace=True)

# Fare（test独有缺失）：用train中位数填充
fare_median = train_df['Fare'].median()
test_df['Fare'].fillna(fare_median, inplace=True)

# 检查后缺失值应为0
print(train_df.isnull().sum())
print(test_df.isnull().sum())

"""### 编码类别特征

"""

# OneHotEncoder（drop='first'避免多重共线性）
encoder = OneHotEncoder(sparse_output=False, drop='first')

# train
encoded_train = encoder.fit_transform(train_df[['Sex', 'Embarked']])
encoded_cols = encoder.get_feature_names_out(['Sex', 'Embarked'])
train_df = pd.concat([train_df.drop(['Sex', 'Embarked'], axis=1),
                      pd.DataFrame(encoded_train, columns=encoded_cols)], axis=1)

# test（用train encoder）
encoded_test = encoder.transform(test_df[['Sex', 'Embarked']])
test_df = pd.concat([test_df.drop(['Sex', 'Embarked'], axis=1),
                     pd.DataFrame(encoded_test, columns=encoded_cols)], axis=1)

print(train_df.head())  # 检查新列：Sex_male, Embarked_Q, Embarked_S

"""### 缩放数值特征（标准化）"""

scaler = StandardScaler()

# data feature
num_features = ['Age', 'Fare']

# train
train_df[num_features] = scaler.fit_transform(train_df[num_features])

# test
test_df[num_features] = scaler.transform(test_df[num_features])

print(train_df[num_features].describe())  # 均值≈0，方差≈1

# save as CSV
train_df.to_csv('preprocessed_train.csv', index=False)
test_df.to_csv('preprocessed_test.csv', index=False)